version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres

  rabbitmq:
    image: "rabbitmq:3-management"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # Management interface
    env_file:
      - .env.rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
